name: CI/CD

on:
  # Tri
  # Trigger the workflow on pull request to master
  pull_request:
    branches: [master]

  # Also allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: github/super-linter@v3
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
#          python -m pip install -r requirements.txt
      - name: Run tests
        run: python tests/test_train.py